src/Entity/Stagiaire.php
<?php

namespace App\Entity;

use App\Repository\StagiaireRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=StagiaireRepository::class)
 */
class Stagiaire
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $telephone;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $diplome;

    /**
     * @ORM\Column(type="date")
     */
    private $date_naiss;

    /**
     * @ORM\Column(type="boolean")
     */
    private $contrat;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $photo;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getDiplome(): ?string
    {
        return $this->diplome;
    }

    public function setDiplome(?string $diplome): self
    {
        $this->diplome = $diplome;

        return $this;
    }

    public function getDateNaiss(): ?\DateTimeInterface
    {
        return $this->date_naiss;
    }

    public function setDateNaiss(\DateTimeInterface $date_naiss): self
    {
        $this->date_naiss = $date_naiss;

        return $this;
    }

    public function getContrat(): ?bool
    {
        return $this->contrat;
    }

    public function setContrat(bool $contrat): self
    {
        $this->contrat = $contrat;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(?string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }
}

src/Form/StagiaireType.php
<?php

namespace App\Form;

use App\Entity\Stagiaire;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;


class StagiaireType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom')
            ->add('prenom')
            ->add('telephone')
            ->add('adresse')
            ->add('diplome')
            ->add('date_naiss', DateType::class,array(
                'widget' => 'choice',
                'years' => range(date('Y')-100, date('Y')),
                'months' => range(1, 12),
                'days' => range(1, 31),
              ))
            ->add('contrat')
            ->add('photo')
            ->add('description')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Stagiaire::class,
        ]);
    }
}

src/Controller/StagiaireController.php
<?php

namespace App\Controller;

use DateTime;
use App\Entity\Stagiaire;
use App\Form\StagiaireType;
use App\Repository\StagiaireRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class StagiaireController extends AbstractController
{
    #[Route('/stagiaire', name: 'stagiaire')]
    public function index(PaginatorInterface $paginator,Request $request): Response
    {
        $repo = $this->getDoctrine()->getRepository(Stagiaire::class);
        $stagiaires = $repo->findAll();
        $stgPagination = $paginator->paginate(
            $stagiaires,
            $request->query->getInt('page',1)
            );
        return $this->render('stagiaire/index.html.twig', [
            'stagiaires' => $stgPagination,
        ]);
    }
    #[Route('stagiaire/new', name: 'stagiaire_new')]
    public function create(){

        $em = $this->getDoctrine()->getManager();

        $sta = new Stagiaire();
        $sta->setNom("Tran");
        $sta->setPrenom("Hugo");
        $sta->setTelephone("0123456789");
        $sta->setAdresse("5 rue de la grande place rouge");
        $sta->setDiplome("Bac+5 du chomage");
        $sta->setContrat(true);
        $sta->setPhoto("https://via.placeholder.com/150/0000FF/808080 ?ford-Mustang");
        $sta->setDescription("Developpeur doué");
        $sta->setDateNaiss(new DateTime('2000-01-01'));
        
        $em->persist($sta);
        $em->flush();
        return $this->redirectToRoute("stagiaire");
    }
    #[Route('stagiaire/add', name: 'stagiaire_add')]
    public function add(Request $request){

        $em = $this->getDoctrine()->getManager();
        $stg = new Stagiaire();
        $form_edit=$this->createForm(StagiaireType::class,$stg);
        $form_edit->handleRequest($request);
        
        if($form_edit->isSubmitted() && $form_edit->isValid()) {
            // dd($form_edit);
            $em->persist($stg);
            $em->flush();
            return $this->redirectToRoute("stagiaire");
        }
        return $this->render("stagiaire/add.html.twig",['form_edit'=>$form_edit->createView()]);
    }

    #[Route('/stagiaire/detail/{id}', name: 'stagiaire_item')]
    public function findOne($id, StagiaireRepository $repo): Response
    {
        $repo = $this->getDoctrine()->getRepository(Stagiaire::class);
        $stagiaire = $repo->find($id);
        // dd($stagiaire);
        return $this->render('stagiaire/detail.html.twig', [
            'stagiaire' => $stagiaire,
        ]);
    }
    
    #[Route('/stagiaire/edit/{id}', name: 'stagiaire_edit')]
    public function edit($id): Response
    {
        $em = $this->getDoctrine()->getManager();
        $stagiaire = $em->getRepository(Stagiaire::class)->find($id);
        if(!$stagiaire){
            throw $this->createNotFoundException(
                'aucun stagiaire ne correspond à l\'id :'.$id
            );
        }
        $stagiaire->setNom('Jean Bernard');
        $em->flush();
        return $this->redirectToRoute('stagiaire');
    }

    #[Route('/stagiaire/update/{id}', name: 'stagiaire_update')]
    public function update($id, Request $request): Response
    {
        $em = $this->getDoctrine()->getManager();
        $stagiaire = $em->getRepository(Stagiaire::class)->find($id);
        $form_edit = $this->createForm(StagiaireType::class,$stagiaire);
        if(!$stagiaire){
            throw $this->createNotFoundException(
                'aucun stagiaire ne correspond à l\'id :'.$id
            );
        }
        $form_edit->handleRequest($request);
        if($form_edit->isSubmitted() && $form_edit->isValid()){
            $em->flush();
            return $this->redirectToRoute('stagiaire_item',['id'=>$id]);
        }
        
        return $this->render('stagiaire/edit.html.twig',['form_edit'=>$form_edit->createView()]);
    }

    #[Route('/stagiaire/delete/{id}', name: 'stagiaire_delete')]
    public function delete($id): Response
    {
        $em = $this->getDoctrine()->getManager();
        $stagiaire = $em->getRepository(Stagiaire::class)->find($id);
        if(!$stagiaire){
            throw $this->createNotFoundException(
                'aucun stagiaire ne correspond à l\'id :'.$id
            );
        }
        $em->remove($stagiaire);
        $em->flush();
        return $this->redirectToRoute('stagiaire');
    }
}

templates/stagiaire/add.html.twig
{% extends 'base.html.twig' %}
{% block body %}
<div class="col-4 offset-4">
<div class="row">
   <div class="col-6">
   {{form_start(form_edit)}}

    {{form_label(form_edit.nom)}} 
    {{form_widget(form_edit.nom)}} 
    {{form_errors(form_edit.nom)}} 

    </div>
    <div class="col-6">
    {{form_label(form_edit.prenom)}} 
    {{form_widget(form_edit.prenom)}} 
    {{form_errors(form_edit.prenom)}} 

    </div>
    {{form_row(form_edit.telephone,{'label' : 'Votre numéro de téléphone'})}}
   {{form_rest(form_edit)}}
   <button class="btn btn-warning col-12">Ajouter</button>
   {{form_end(form_edit)}}
   </div>
   </div>
{% endblock %}

templates/stagiaire/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello stagiaireController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em stagiaire; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="container">
    <h1>Liste des stagiaires</h1>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Id</th>
                <th>nom</th>
                <th>prenom</th>
                <th>telephone</th>
                <th>adresse</th>
                <th>diplome</th>
                <th>date de naissance</th>
                <th>contrat</th>
                <th>photo</th>
                <th>description</th>
            </tr>
        </thead>
        <tbody>
        
            <tr>
                <td>{{stagiaire.id}}</td>
                <td>{{stagiaire.nom}}</td>
                <td>{{stagiaire.prenom}}</td>
                <td>{{stagiaire.telephone}}</td>
                <td>{{stagiaire.adresse}}</td>
                <td>{{stagiaire.diplome}}</td>
                <td>{{stagiaire.dateNaiss|date('d-m-Y')}}</td>
                <td>{{stagiaire.contrat}}</td>
                <td><img src="{{ asset('' ~ stagiaire.photo)}}"></td>
                <td>{{stagiaire.description}}</td>
                
               
            </tr>
            
        </tbody>

    </table>
</div>
{% endblock %}

templates/stagiaire/edit.html.twig
{% extends 'base.html.twig' %}
{% block body %}
<div class="col-4 offset-4">
<div class="row">
   <div class="col-6">
   {{form_start(form_edit)}}

    {{form_label(form_edit.nom)}} 
    {{form_widget(form_edit.nom)}} 
    {{form_errors(form_edit.nom)}} 

    </div>
    <div class="col-6">
    {{form_label(form_edit.prenom)}} 
    {{form_widget(form_edit.prenom)}} 
    {{form_errors(form_edit.prenom)}} 

    </div>
    {{form_row(form_edit.telephone,{'label' : 'Votre numéro de téléphone'})}}
   {{form_rest(form_edit)}}
   <button class="btn btn-warning col-12">Editer</button>
   {{form_end(form_edit)}}
   </div>
   </div>
{% endblock %}

templates/stagiaire/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello stagiaireController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em stagiaire; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="container">
    <h1>Liste des stagiaires</h1>
    <a href="{{path('stagiaire_add')}}" class="btn btn-primary"></i>Ajouter un stagiaire</a>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Id</th>
                <th>nom</th>
                <th>prenom</th>
                <th>telephone</th>
                <th>adresse</th>
                <th>diplome</th>
                <th>date de naissance</th>
                <th>contrat</th>
                <th>photo</th>
                <th>description</th>
                <th>options</th>

            </tr>
        </thead>
        <tbody>
        {% for stagiaire in stagiaires %}
            <tr>
                <td>{{stagiaire.id}}</td>
                <td>{{stagiaire.nom}}</td>
                <td>{{stagiaire.prenom}}</td>
                <td>{{stagiaire.telephone}}</td>
                <td>{{stagiaire.adresse}}</td>
                <td>{{stagiaire.diplome}}</td>
                {% if stagiaire.dateNaiss is empty %}
                <td>Non défini</td>
                {% else %}
                <td>{{stagiaire.dateNaiss|date('d-m-Y')}}</td>
                {% endif %}
                {% if stagiaire.contrat == true %}
                <td>oui</td>
                {% else %}
                <td>non</td>
                {% endif %}
                <td><img src="{{ asset('' ~ stagiaire.photo)}}"></td>
                <td>{{stagiaire.description}}</td>
                
                <td>
                    <a href="{{path('stagiaire_item',{id:stagiaire.id})}}" class="btn btn-primary"><i class="fas fa-pen"></i>Détail</a>
                    <a href="{{path('stagiaire_update',{id:stagiaire.id})}}" class="btn btn-info"><i class="fas fa-pen"></i>Editer</a>
                    <a onclick="return confirm('Êtes-vous sûr de vouloir supprimer ?')" href="{{path('stagiaire_delete',{id:stagiaire.id})}}" class="btn btn-danger"><i class="fas fa-pen"></i>Supprimer</a>
                    {# <a href="stagiaire/{{stagiaire.id}}" class="btn btn-info"><i class="fas fa-pen"></i>Détail</a> #}
                </td>
            </tr>
            {% endfor %}
        </tbody>

    </table>
    <div class="d-flex justify-content-center">{{ knp_pagination_render(stagiaires) }}</div>
</div>
{% endblock %}